# Premium Linux Zsh aliases
alias gs='git status --short --branch'
alias ga='git add -A'
alias gc='git commit -m'
alias gp='git push'
alias gl='git log --oneline --graph --decorate --all'
alias gd='git diff'
alias gco='git checkout'
alias ..='cd ..'
alias ...='cd ../..'
alias ll='ls -lah'
alias la='ls -A'
alias c='clear'
alias py='python3'
alias pip='python3 -m pip'
alias venv='python3 -m venv .venv'
alias activate='source .venv/bin/activate'
alias ni='npm install'
alias nd='npm run dev'
alias nb='npm run build'
alias ns='npm start'
alias h='history'
alias path='printf "%s\\n" "$PATH" | tr ":" "\\n"'
command -v eza >/dev/null && alias ls='eza --group-directories-first'
command -v bat >/dev/null && alias cat='bat --paging=never'
command -v rg >/dev/null && alias grep='rg'
command -v zoxide >/dev/null && eval "$(zoxide init zsh)"
command -v claude >/dev/null && alias cl='claude'
command -v aider >/dev/null && alias ad='aider'
command -v openclaw >/dev/null && alias oc='openclaw'
